<#!
Summarize an SLM Blender pipeline run report (report.json) as a single stable JSON line.

This is Blender-free and intended for downstream tooling.

Examples:
  pwsh -NoProfile -File slm-tool/scripts/summarize_run.ps1 -ReportPath .\slm-tool\_runs\export-smoke-...\report.json
  pwsh -NoProfile -File slm-tool/scripts/summarize_run.ps1 -RunDir .\slm-tool\_runs\export-smoke-...
#>

[CmdletBinding()]
param(
  [Parameter(Mandatory=$false)]
  [string]$ReportPath,

  [Parameter(Mandatory=$false)]
  [string]$RunDir
)

$ErrorActionPreference = 'Stop'

if (-not $ReportPath -and -not $RunDir) {
  throw "summarize_run requires -ReportPath <path-to-report.json> or -RunDir <run-directory>"
}

if (-not $ReportPath) {
  $ReportPath = Join-Path $RunDir 'report.json'
}

$resolved = (Resolve-Path $ReportPath).Path

# Read as UTF-8 (report.json is generated by Python; should already be UTF-8).
$raw = Get-Content -LiteralPath $resolved -Raw -Encoding UTF8
$report = $raw | ConvertFrom-Json

$export = $report.export
$daeBytes = $null
$daePath  = $null
if ($export) {
  $daeBytes = $export.collada_dae_bytes
  $daePath  = $export.collada_dae
}

$out = [ordered]@{
  ok             = $true
  status         = $report.status
  preset         = $report.preset
  input          = $report.input
  input_ext      = $report.input_ext
  objects        = $report.objects
  triangles_approx= $report.triangles_approx
  dae_bytes      = $daeBytes
  dae_path       = $daePath
  duration_ms    = $report.run.duration_ms
  blender        = $report.tool.blender
}

# Emit a single line JSON object for easy capture.
$out | ConvertTo-Json -Depth 6 -Compress | Write-Output
